### ISSUE TITLE
Nakon aktivacije, plugin prouzroči Fatal error

### ISSUE THREAD

**Issue by spikey979** [ne-znam/woocommerce-racuni-fiskalizacija#4]
**Describe the bug**
Nakon aktivacije plugina, WP izbaci:
Fatal error:  Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/woocommerce-racuni-fiskalizacija-master/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/woocommerce-racuni-fiskalizacija-master/neznam-racuni-fiskalizacija.php:23

Navedeno je zapravo logično jer unutar /var/www/html/wp-content/plugins/woocommerce-racuni-fiskalizacija-master/   ne postoji folder **vendor** sa fajlom **autoload.php**…

Plugin sam skinuo kao zip fajl sa https://github.com/ne-znam/woocommerce-racuni-fiskalizacija 
Prenio sam ga kroz Dodaci sučelje u WordPressu
Nakon što kliknem na Aktiviraj, sve se sruši s gore navedenim errorom

Da li možda postoji više verzija pa sam skinuo krivu?
Može li pomoć?

**Comment by mbanusic** [comment]
Ako samo preuzmeš s githuba onda je potrebno odraditi `composer install` unutar plugin direktorija. Zbog toga se javlja ova poruka. Kad pripremam za instalalaciju onda to ja odradim i spakiram u zip. Mogu sada pripremiti takav zip s ovim zadnjim izmjenama pa da možeš probati? Ili samo samo pokreni composer.

**Comment by spikey979** [comment]
Baš sam malo prije isprobavao pa sam composer install odradio lokalno kod sebe i to radi ok, međutim kad to ubacim u zip i preselim na server, tamo se žali na verziju php-a i svašta nešto... sad pokušavam odraditi composer install na serveru, ali tamo to ne mogu odraditi... Ako vam nije problem, možete li pripremiti takav zip pa da ga probam ubaciti?

**Comment by mbanusic** [comment]
Evo ovdje sam stavio najnoviju verziju https://github.com/ne-znam/woocommerce-racuni-fiskalizacija/releases/tag/v0.2.0-alpha

Svakako provjerite da na serveru imate noviju verziju PHPa

**Comment by spikey979** [comment]
Hvala vam

**Comment by mbanusic** [comment]
Postavke su pod Porez/Tax

<img width="756" alt="Screenshot 2023-03-02 at 12 07 36" src="https://user-images.githubusercontent.com/694907/222411628-2e84e9c1-33a2-48a0-98b2-152997070594.png">
